services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=drexel
      - POSTGRES_USER={dbUser}
      - POSTGRES_PASSWORD={dbPassword}
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/drexel
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db