services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER={dbUser}
      - POSTGRES_PASSWORD={dbPassword}
      - POSTGRES_DB=drexel
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  app:
    build: .
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/drexel
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db